  
version: '3'
services:
  nodejs-graphql:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "4000:4000"
    container_name: graphql-projeto-final-back
    volumes:
       - ./:/usr/src/app/api
       - /usr/src/app/api/node_modules
    networks:
      - graphql-net

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # Accept remote connections
      MYSQL_ROOT_HOST: '%'   
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    container_name: graphql-projeto-final-db
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - graphql-net

networks:
  graphql-net:
    driver: bridge
    
# Names our volume
volumes:
  my-db:
